/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://iwqzsjmnhbdk3k654jiauc734i.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-b5tkwlnxkzevzpdc3pczttugqa",
    "aws_cognito_identity_pool_id": "us-east-1:dc26b9c7-9b2b-4168-aa6c-e8f02557ba78",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_lxFghzyBv",
    "aws_user_pools_web_client_id": "h6cbo1t6t286oj5m1g56jdmff",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "PHONE_NUMBER",
        "EMAIL",
        "FAMILY_NAME",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "djibinhobucket153126-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
